'use client';
export const sampleNotifications = [
    {
        id: 1,
        type: "info",
        message: "System maintenance scheduled at midnight.",
        description: "The server will be down from 12:00 AM to 2:00 AM.",
        timestamp: "2025-07-09T08:15:00Z",
        read: false,
    },
    {
        id: 2,
        type: "warning",
        message: "Your password will expire soon.",
        description: "Please update your password within the next 5 days.",
        timestamp: "2025-07-08T13:45:00Z",
        read: false,
    },
    {
        id: 3,
        type: "success",
        message: "Your payment was successful.",
        description: "Invoice #9321 has been paid.",
        timestamp: "2025-07-07T10:30:00Z",
        read: true,
    },
    {
        id: 4,
        type: "error",
        message: "Failed to upload report.",
        description: "There was a server error while uploading file.csv.",
        timestamp: "2025-07-09T01:20:00Z",
        read: false,
    },
    {
        id: 5,
        type: "info",
        message: "New feature released: Dark Mode!",
        description: "Go to Settings to switch to the new dark mode.",
        timestamp: "2025-07-06T18:05:00Z",
        read: true,
    },
    {
        id: 6,
        type: "success",
        message: "Account linked successfully.",
        description: "Your bank account has been linked to your profile.",
        timestamp: "2025-07-05T09:12:00Z",
        read: true,
    },
    {
        id: 7,
        type: "error",
        message: "Payment method declined.",
        description: "Please update your credit card information.",
        timestamp: "2025-07-04T17:32:00Z",
        read: false,
    },
    {
        id: 8,
        type: "warning",
        message: "Unusual login attempt detected.",
        description: "Someone tried to log in from a new device.",
        timestamp: "2025-07-03T22:40:00Z",
        read: false,
    },
    {
        id: 9,
        type: "info",
        message: "Weekly digest is ready.",
        description: "Check out your weekly activity summary.",
        timestamp: "2025-07-02T07:25:00Z",
        read: true,
    },
    {
        id: 10,
        type: "success",
        message: "You’ve earned a reward!",
        description: "Thanks for being an active user. Claim your badge now.",
        timestamp: "2025-07-01T19:55:00Z",
        read: true,
    },
    {
        id: 11,
        type: "warning",
        message: "Storage space running low.",
        description: "You’ve used 90% of your storage capacity.",
        timestamp: "2025-06-30T14:50:00Z",
        read: false,
    },
    {
        id: 12,
        type: "error",
        message: "Sync failed.",
        description: "Unable to sync data with the server.",
        timestamp: "2025-06-29T11:10:00Z",
        read: true,
    },
    {
        id: 13,
        type: "info",
        message: "New comment on your post.",
        description: "John Doe commented: 'Great update!'",
        timestamp: "2025-06-28T15:45:00Z",
        read: false,
    },
    {
        id: 14,
        type: "success",
        message: "Backup completed.",
        description: "Your data was backed up successfully.",
        timestamp: "2025-06-27T02:00:00Z",
        read: true,
    },
    {
        id: 15,
        type: "warning",
        message: "Trial period ending soon.",
        description: "Your free trial ends in 2 days. Upgrade now.",
        timestamp: "2025-06-26T21:30:00Z",
        read: false,
    },
    {
        id: 16,
        type: "info",
        message: "New version available.",
        description: "Update to v3.4.0 for new features and fixes.",
        timestamp: "2025-06-25T10:15:00Z",
        read: false,
    },
    {
        id: 17,
        type: "error",
        message: "App crashed unexpectedly.",
        description: "Crash report sent to development team.",
        timestamp: "2025-06-24T16:45:00Z",
        read: true,
    },
    {
        id: 18,
        type: "success",
        message: "Settings saved.",
        description: "Your preferences were updated successfully.",
        timestamp: "2025-06-23T13:20:00Z",
        read: true,
    },
    {
        id: 19,
        type: "info",
        message: "You have new followers.",
        description: "3 new people followed you this week.",
        timestamp: "2025-06-22T08:50:00Z",
        read: true,
    },
    {
        id: 20,
        type: "warning",
        message: "System update required.",
        description: "Your version is outdated. Please update to continue.",
        timestamp: "2025-06-21T23:15:00Z",
        read: false,
    }
];
